import { games } from '../config/games.js';
import { readJson } from '../utils/storage.js';

const assetStyles = document.createElement('link'); assetStyles.rel = 'stylesheet'; assetStyles.href = './_game-center/styles/gravity-tourist-assets.css?v=1'; document.head.append(assetStyles);
const leaderStyles = document.createElement('link'); leaderStyles.rel = 'stylesheet'; leaderStyles.href = './_game-center/styles/game-center-leaderboard.css?v=1'; document.head.append(leaderStyles);
const trophyStyles = document.createElement('link'); trophyStyles.rel = 'stylesheet'; trophyStyles.href = './_game-center/styles/leaderboard-trophy.css?v=1'; document.head.append(trophyStyles);
const compactTrophyStyles = document.createElement('link'); compactTrophyStyles.rel = 'stylesheet'; compactTrophyStyles.href = './_game-center/styles/leaderboard-trophy-compact.css?v=1'; document.head.append(compactTrophyStyles);

const grid = document.querySelector('#game-grid');
const formatTime = seconds => seconds ? `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, '0')}` : '—';
for (const game of games) {
  const records = readJson(game.storageKey, { highScore: 0, longestSurvival: 0 });
  const card = document.createElement('article'); card.className = 'game-card';
  card.innerHTML = `<div class="game-art" aria-hidden="true"><span class="scan-grid"></span><span class="planet-glow"></span><span class="preview-route"></span><span class="preview-planet"><i></i></span><span class="preview-asteroid"></span><span class="earth"><i></i></span><span class="orbit orbit-a"></span><span class="orbit orbit-b"></span><span class="ufo"><i class="dome"></i><i class="ship"></i><i class="beam"></i></span><span class="target target-a"></span><span class="target target-b"></span><span class="signal"><i></i> TOURISM // NOT INVASION</span><span class="mission-id">MISSION 001</span></div><div class="game-copy"><div class="card-top"><span>${game.eyebrow}</span><b><i></i>${game.status}</b></div><div class="title-row"><div><small>FEATURED MISSION</small><h2>${game.title}</h2></div><span class="rating">SKILL<b>∞</b></span></div><p class="story-lead">${game.description}</p><p class="story-detail">${game.story}</p><dl><div><dt>Điểm cao</dt><dd>${Number(records.highScore).toLocaleString('vi-VN')}</dd></div><div><dt>Sống lâu nhất</dt><dd>${formatTime(records.longestSurvival)}</dd></div></dl><section class="center-leaders"><header><span>♛ GLOBAL TOP 3</span><a href="${game.href}?leaderboard=1">XEM ĐẦY ĐỦ →</a></header><div id="center-leader-list">Đang tải bảng xếp hạng...</div></section><a class="play-button" href="${game.href}"><span class="play-icon">▶</span><span class="play-copy"><b>PLAY NOW</b><small>Bắt đầu hành trình tới Trái Đất</small></span><span class="play-arrow">→</span></a></div>`;
  const oldLeaders = card.querySelector('.center-leaders');
  if (oldLeaders) oldLeaders.outerHTML = `<a class="leaderboard-trophy" href="${game.href}?leaderboard=1" aria-label="Open Gravity Tourist leaderboard"><span>🏆</span><b>LEADERBOARD</b><small>PLAYER RANKINGS</small><i>→</i></a>`;
  grid.append(card);
}

const canvas = document.querySelector('#game-center-starfield'), context = canvas?.getContext('2d');
if (canvas && context) {
  const compact = matchMedia('(max-width:700px),(pointer:coarse)').matches, reducedMotion = matchMedia('(prefers-reduced-motion:reduce)').matches;
  let stars = [], meteors = [], lastFrame = 0, meteorTimer = 3200;
  const createStars = () => { const count = Math.min(compact ? 180 : 330, Math.max(compact ? 125 : 220, Math.round(innerWidth * innerHeight / 3900))); stars = Array.from({ length: count }, () => { const flare = Math.random() > .94; return { x: Math.random() * innerWidth, y: Math.random() * innerHeight, size: flare ? 1.2 + Math.random() * 1.8 : .3 + Math.random() * 1.05, alpha: .18 + Math.random() * .78, phase: Math.random() * Math.PI * 2, speed: .0007 + Math.random() * .0024, drift: .006 + Math.random() * .022, tint: Math.random() > .78 ? (Math.random() > .5 ? '104,225,255' : '178,156,255') : '235,244,255', diamond: Math.random() > .88, flare }; }); };
  const resize = () => { const ratio = Math.min(devicePixelRatio || 1, compact ? 1 : 1.5); canvas.width = Math.round(innerWidth * ratio); canvas.height = Math.round(innerHeight * ratio); canvas.style.width = `${innerWidth}px`; canvas.style.height = `${innerHeight}px`; context.setTransform(ratio, 0, 0, ratio, 0, 0); createStars(); };
  const shootingStar = () => meteors.push({ x: innerWidth * (.25 + Math.random() * .75), y: -35, vx: -(5 + Math.random() * 4), vy: 4 + Math.random() * 3, length: 75 + Math.random() * 70, life: 1 });
  const draw = time => { requestAnimationFrame(draw); if (document.hidden || time - lastFrame < (reducedMotion ? 120 : compact ? 42 : 26)) return; lastFrame = time; context.clearRect(0, 0, innerWidth, innerHeight);
    for (const star of stars) { const alpha = star.alpha * (.56 + Math.sin(time * star.speed + star.phase) * .44); star.y += star.drift; if (star.y > innerHeight + 8) star.y = -8; context.save(); context.fillStyle = `rgba(${star.tint},${alpha})`; if(star.flare){context.shadowBlur=12+star.size*5;context.shadowColor=`rgba(${star.tint},${alpha})`;const halo=context.createRadialGradient(star.x,star.y,0,star.x,star.y,star.size*9);halo.addColorStop(0,`rgba(${star.tint},${alpha*.42})`);halo.addColorStop(1,`rgba(${star.tint},0)`);context.fillStyle=halo;context.fillRect(star.x-star.size*9,star.y-star.size*9,star.size*18,star.size*18);context.strokeStyle=`rgba(${star.tint},${alpha*.62})`;context.lineWidth=.55;context.beginPath();context.moveTo(star.x-star.size*8,star.y);context.lineTo(star.x+star.size*8,star.y);context.moveTo(star.x,star.y-star.size*8);context.lineTo(star.x,star.y+star.size*8);context.stroke();context.fillStyle=`rgba(${star.tint},${alpha})`;} context.beginPath(); if (star.diamond) { context.moveTo(star.x, star.y - star.size * 2.8); context.lineTo(star.x + star.size * .62, star.y); context.lineTo(star.x, star.y + star.size * 2.8); context.lineTo(star.x - star.size * .62, star.y); context.closePath(); } else context.arc(star.x, star.y, star.size, 0, Math.PI * 2); context.fill(); context.restore(); }
    if (!reducedMotion && time > meteorTimer) { shootingStar(); meteorTimer = time + 5500 + Math.random() * 6500; }
    for (let i = meteors.length - 1; i >= 0; i--) { const m = meteors[i]; m.x += m.vx; m.y += m.vy; m.life -= .014; const l = Math.hypot(m.vx, m.vy), g = context.createLinearGradient(m.x, m.y, m.x - m.vx / l * m.length, m.y - m.vy / l * m.length); g.addColorStop(0, `rgba(215,250,255,${m.life})`); g.addColorStop(1, 'rgba(80,190,255,0)'); context.strokeStyle = g; context.lineWidth = 1.4; context.beginPath(); context.moveTo(m.x, m.y); context.lineTo(m.x - m.vx / l * m.length, m.y - m.vy / l * m.length); context.stroke(); if (m.life <= 0 || m.y > innerHeight + 100) meteors.splice(i, 1); }
  };
  addEventListener('resize', resize, { passive: true }); resize(); requestAnimationFrame(draw);
}
