const VIEW_HEIGHT = 960;

export class GameRenderer {
  constructor(canvas, engine) {
    this.canvas = canvas; this.ctx = canvas.getContext('2d', { alpha: false }); this.engine = engine; this.introProgress = -1;
    this.ufoImage = this.loadImage('./assets/images/tourist-ufo-v2.png');
    this.celestialAtlas = this.loadImage('./assets/images/celestial-atlas-v1.png');
    this.spaceBackground = this.loadImage('./assets/images/deep-space-background-v1.png');
    this.reactionAtlas = new Image(); this.celestialAtlasV2 = new Image(); this.hazardAtlas = new Image(); this.reactionUntil = 0; this.reactionIndex = 0;
    const loadSecondary=()=>{this.reactionAtlas=this.loadImage('./assets/images/alien-reactions-v1.png');this.celestialAtlasV2=this.loadImage('./assets/images/celestial-atlas-v2.png');this.hazardAtlas=this.loadImage('./assets/images/hazard-atlas-v1.png');};
    if('requestIdleCallback'in window)requestIdleCallback(loadSecondary,{timeout:1800});else setTimeout(loadSecondary,700);
    this.stars = Array.from({ length: 190 }, () => { const distance = Math.random(); return { x: Math.random(), y: Math.random(), depth: .035 + (1 - distance) * .22, r: distance < .72 ? .35 + Math.random() * .75 : .9 + Math.random() * 1.35, a: .24 + Math.random() * .7, speed: .0015 + Math.random() * .0035, diamond: Math.random() > .78, tint: Math.random() > .84 ? (Math.random() > .5 ? '174, 224, 255' : '205, 190, 255') : '255, 255, 255' }; });
    this.resize(); window.addEventListener('resize', this.resize);
  }
  loadImage(src){const image=new Image();image.decoding='async';image.src=src;return image;}
  resize = () => {
    const rect = this.canvas.getBoundingClientRect(), dpr = Math.min(devicePixelRatio || 1, 2);
    this.canvas.width = Math.max(1, Math.round(rect.width * dpr)); this.canvas.height = Math.max(1, Math.round(rect.height * dpr));
    this.scale = this.canvas.height / VIEW_HEIGHT; this.viewWidth = this.canvas.width / this.scale; this.offsetX = 0;
  };
  render() {
    const ctx = this.ctx, e = this.engine;
    ctx.setTransform(1, 0, 0, 1, 0, 0); ctx.fillStyle = '#02050e'; ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    ctx.setTransform(this.scale, 0, 0, this.scale, 0, 0); this.background(ctx, e.difficulty.progress); this.earth(ctx, e.difficulty.progress); this.infrastructure(ctx, e.difficulty.progress); this.humanDefense(ctx, e.difficulty.progress);
    const side = (this.viewWidth - 540) / 2; ctx.save(); ctx.translate(side, VIEW_HEIGHT + e.cameraX); ctx.transform(0, -1, 1, 0, 0, 0);
    this.trails(ctx); for (const body of e.bodies) this.body(ctx, body); for (const item of e.debris) this.debris(ctx, item);
    if (this.introProgress < 0) this.ufo(ctx, e.ufo); ctx.restore();
    if (this.introProgress >= 0) { this.introUfo(ctx, this.introProgress, side); this.failureAlert(ctx, this.introProgress, side); } else this.activeReaction(ctx, side, e);
    this.vignette(ctx);
  }
  background(ctx, progress) {
    const g = ctx.createRadialGradient(this.viewWidth / 2, 130, 20, this.viewWidth / 2, 400, Math.max(this.viewWidth, 800)); g.addColorStop(0, progress > .55 ? '#132d63' : '#101c46'); g.addColorStop(.55, '#070d25'); g.addColorStop(1, '#02050e'); ctx.fillStyle = g; ctx.fillRect(0, 0, this.viewWidth, VIEW_HEIGHT);
    if (this.spaceBackground.complete && this.spaceBackground.naturalWidth) { ctx.globalAlpha = .72; const ir = this.spaceBackground.naturalWidth / this.spaceBackground.naturalHeight, vr = this.viewWidth / VIEW_HEIGHT; let sw = this.spaceBackground.naturalWidth, sh = this.spaceBackground.naturalHeight, sx = 0, sy = 0; if (ir > vr) { sw = sh * vr; sx = (this.spaceBackground.naturalWidth - sw) / 2; } else { sh = sw / vr; sy = (this.spaceBackground.naturalHeight - sh) / 2; } ctx.drawImage(this.spaceBackground, sx, sy, sw, sh, 0, 0, this.viewWidth, VIEW_HEIGHT); ctx.globalAlpha = 1; }
    const now = performance.now() * .001; for (const star of this.stars) { star.a += star.speed; if (star.a > 1 || star.a < .1) star.speed = -star.speed; const x = star.x * this.viewWidth, y = (star.y * VIEW_HEIGHT + progress * 70 * star.depth) % VIEW_HEIGHT, color = `rgba(${star.tint}, ${star.a})`; if (star.diamond) this.diamondStar(ctx, x, y, star.r * 2, star.r * .4, color); else { ctx.fillStyle = color; ctx.beginPath(); ctx.arc(x, y, star.r, 0, Math.PI * 2); ctx.fill(); } }
    this.spaceLights(ctx, now);
    ctx.strokeStyle = '#5b83cc13'; ctx.lineWidth = 1; for (let y = 180; y < VIEW_HEIGHT; y += 120) { ctx.beginPath(); ctx.moveTo(this.viewWidth * .15, y); ctx.lineTo(this.viewWidth * .85, y); ctx.stroke(); }
  }
  spaceLights(ctx, now) {
    ctx.save(); ctx.globalCompositeOperation = 'screen';
    for (let ribbon = 0; ribbon < 3; ribbon++) { const y = 260 + ribbon * 210 + Math.sin(now * .18 + ribbon * 2.1) * 44; const gradient = ctx.createLinearGradient(0, y, this.viewWidth, y + 60); gradient.addColorStop(0, '#37e7ff00'); gradient.addColorStop(.22, ribbon === 1 ? '#9b5cff26' : '#2fffdc20'); gradient.addColorStop(.65, '#4b70ff24'); gradient.addColorStop(1, '#37e7ff00'); ctx.strokeStyle = gradient; ctx.lineWidth = 22 + ribbon * 7; ctx.filter = 'blur(12px)'; ctx.beginPath(); ctx.moveTo(-80, y); ctx.bezierCurveTo(this.viewWidth * .25, y - 120, this.viewWidth * .66, y + 135, this.viewWidth + 80, y - 35); ctx.stroke(); }
    ctx.filter = 'none';
    ctx.restore();
  }
  diamondStar(ctx, cx, cy, outerRadius, innerRadius, fillStyle) { let rotation = Math.PI * 1.5; const step = Math.PI / 4; ctx.beginPath(); ctx.moveTo(cx, cy - outerRadius); for (let i = 0; i < 4; i++) { ctx.lineTo(cx + Math.cos(rotation) * outerRadius, cy + Math.sin(rotation) * outerRadius); rotation += step; ctx.lineTo(cx + Math.cos(rotation) * innerRadius, cy + Math.sin(rotation) * innerRadius); rotation += step; } ctx.closePath(); ctx.fillStyle = fillStyle; ctx.fill(); }
  earth(ctx, progress) {
    const radius = 72 + progress * 245, x = this.viewWidth / 2, y = 18 + progress * 15;
    const aura = ctx.createRadialGradient(x, y, radius * .45, x, y, radius * 1.65); aura.addColorStop(0, '#3eb7ff55'); aura.addColorStop(.65, '#246dff22'); aura.addColorStop(1, '#194cff00'); ctx.fillStyle = aura; ctx.beginPath(); ctx.arc(x, y, radius * 1.65, 0, Math.PI * 2); ctx.fill();
    ctx.save(); ctx.beginPath(); ctx.arc(x, y, radius, 0, Math.PI * 2); ctx.clip(); const ocean = ctx.createRadialGradient(x - radius * .36, y - radius * .4, radius * .05, x, y, radius); ocean.addColorStop(0, '#d9ffff'); ocean.addColorStop(.12, '#65d7ff'); ocean.addColorStop(.55, '#1674ca'); ocean.addColorStop(1, '#06183f'); ctx.fillStyle = ocean; ctx.fillRect(x - radius, y - radius, radius * 2, radius * 2);
    if (this.celestialAtlas.complete && this.celestialAtlas.naturalWidth) ctx.drawImage(this.celestialAtlas, 0, 0, 512, 512, x - radius * 1.28, y - radius * 1.28, radius * 2.56, radius * 2.56);
    ctx.fillStyle = '#ffffffb5'; ctx.beginPath(); ctx.ellipse(x - radius * .12, y - radius * .69, radius * .52, radius * .12, -.12, 0, Math.PI * 2); ctx.fill(); ctx.restore(); ctx.strokeStyle = '#9ae9ff66'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(x, y, radius + 3, 0, Math.PI * 2); ctx.stroke();
  }
  continent(ctx, x, y, scale, points) { ctx.beginPath(); points.forEach(([px, py], i) => i ? ctx.lineTo(x + px * scale, y + py * scale) : ctx.moveTo(x + px * scale, y + py * scale)); ctx.closePath(); ctx.fill(); }
  infrastructure(ctx, progress) {
    const alpha = .32 + progress * .48; ctx.save(); ctx.globalAlpha = alpha;
    const satellite = (x, y, size, rotation) => { ctx.save(); ctx.translate(x, y); ctx.rotate(rotation); ctx.fillStyle = '#b8c6dc'; ctx.fillRect(-size * .18, -size * .22, size * .36, size * .44); ctx.fillStyle = '#1758a5'; ctx.strokeStyle = '#53a9ff'; ctx.lineWidth = 1; ctx.fillRect(-size, -size * .25, size * .7, size * .5); ctx.strokeRect(-size, -size * .25, size * .7, size * .5); ctx.fillRect(size * .3, -size * .25, size * .7, size * .5); ctx.strokeRect(size * .3, -size * .25, size * .7, size * .5); ctx.restore(); };
    satellite(this.viewWidth * .18, 420, 25, -.35); satellite(this.viewWidth * .81, 535, 20, .22);
    if (progress > .28) { ctx.save(); ctx.translate(this.viewWidth * .73, 650); ctx.strokeStyle = '#56cfff'; ctx.shadowBlur = 16; ctx.shadowColor = '#3fcfff'; ctx.lineWidth = 4; ctx.beginPath(); ctx.ellipse(0, 0, 52, 18, -.12, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = '#a9b8d2'; ctx.beginPath(); ctx.arc(0, 0, 16, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#15233b'; ctx.beginPath(); ctx.arc(0, 0, 8, 0, Math.PI * 2); ctx.fill(); ctx.restore(); }
    if (progress > .5) { ctx.strokeStyle = '#3f9cff66'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(this.viewWidth * .12, 805); ctx.lineTo(this.viewWidth * .88, 715); ctx.stroke(); ctx.fillStyle = '#64bcff'; ctx.font = '800 8px ui-monospace,monospace'; ctx.fillText('ORBITAL CARGO LANE', this.viewWidth * .72, 725); }
    ctx.restore();
  }
  humanDefense(ctx, progress) {
    if (progress < .22) return; const count = 1 + Math.floor(progress * 4); ctx.save(); ctx.strokeStyle = `rgba(255,93,110,${.16 + progress * .36})`; ctx.setLineDash([10, 16]); ctx.lineWidth = 1.5;
    for (let i = 0; i < count; i++) { const y = 185 + i * 92, shift = (i % 2 ? 1 : -1) * this.viewWidth * .16; ctx.beginPath(); ctx.moveTo(this.viewWidth / 2 + shift, y); ctx.lineTo(this.viewWidth / 2 - shift * .35, y + 250); ctx.stroke(); ctx.fillStyle = '#ff7180'; ctx.fillRect(this.viewWidth / 2 + shift - 7, y - 3, 14, 6); }
    ctx.setLineDash([]); ctx.fillStyle = '#ff8d99'; ctx.font = '800 8px ui-monospace,monospace'; ctx.textAlign = 'right'; ctx.fillText(progress > .7 ? 'ORBITAL DEFENSE: ACTIVE' : 'TRACKING SIGNAL…', this.viewWidth - 24, 150); ctx.restore();
  }
  routes(ctx, bodies, ufo) {
    const targets = bodies.filter(body => body !== ufo.orbitBody && body.x > ufo.x - 20).sort((a, b) => a.x - b.x).slice(0, 3);
    for (const body of targets) { ctx.save(); ctx.strokeStyle = body.route === 'risk' ? '#ff9d42aa' : body.route === 'medium' ? '#ff50b0aa' : '#48f0b5aa'; ctx.lineWidth = 1.8; ctx.setLineDash([8, 8]); ctx.beginPath(); ctx.moveTo(ufo.x, ufo.y); const midX = (ufo.x + body.x) / 2, bend = body.y > ufo.y ? -34 : 34; ctx.quadraticCurveTo(midX, (ufo.y + body.y) / 2 + bend, body.x, body.y); ctx.stroke(); ctx.setLineDash([]); ctx.restore(); }
  }
  body(ctx, body) {
    ctx.save(); ctx.translate(body.x, body.y); const orbitGradient=ctx.createLinearGradient(-body.captureRadius,0,body.captureRadius,0);orbitGradient.addColorStop(0,body.glow+'08');orbitGradient.addColorStop(.28,body.glow+'b8');orbitGradient.addColorStop(.62,'#ffffff66');orbitGradient.addColorStop(1,body.glow+'10');ctx.shadowBlur=10;ctx.shadowColor=body.glow;ctx.strokeStyle=orbitGradient;ctx.lineWidth=1.25;ctx.setLineDash([2,7]);ctx.beginPath();ctx.arc(0,0,body.captureRadius,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.5;ctx.lineWidth=.65;ctx.setLineDash([]);ctx.beginPath();ctx.arc(0,0,body.captureRadius+5,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;ctx.shadowBlur=0;
    const glow = ctx.createRadialGradient(0, 0, body.radius * .25, 0, 0, body.radius * 2.5); glow.addColorStop(0, body.glow + 'aa'); glow.addColorStop(1, body.glow + '00'); ctx.fillStyle = glow; ctx.beginPath(); ctx.arc(0, 0, body.radius * 2.5, 0, Math.PI * 2); ctx.fill();
    const atlasIndex = this.atlasIndex(body); const atlasReady = this.celestialAtlas.complete && this.celestialAtlas.naturalWidth;
    ctx.save(); ctx.beginPath(); ctx.arc(0, 0, body.radius, 0, Math.PI * 2); ctx.clip(); const planet = ctx.createRadialGradient(-body.radius * .38, -body.radius * .45, 1, 0, 0, body.radius); planet.addColorStop(0, '#f7ffff'); planet.addColorStop(.16, body.color); planet.addColorStop(1, '#080d24'); ctx.fillStyle = planet; ctx.fillRect(-body.radius, -body.radius, body.radius * 2, body.radius * 2);
    if (atlasReady && atlasIndex !== 5) { const sx = atlasIndex % 3 * 512, sy = Math.floor(atlasIndex / 3) * 512; ctx.drawImage(this.celestialAtlas, sx, sy, 512, 512, -body.radius * 1.35, -body.radius * 1.35, body.radius * 2.7, body.radius * 2.7); }
    const modernIndex=this.modernAtlasIndex(body);if(modernIndex>=0&&this.celestialAtlasV2.complete&&this.celestialAtlasV2.naturalWidth){const sw=this.celestialAtlasV2.naturalWidth/4,sh=this.celestialAtlasV2.naturalHeight/2,sx=modernIndex%4*sw,sy=Math.floor(modernIndex/4)*sh;ctx.drawImage(this.celestialAtlasV2,sx,sy,sw,sh,-body.radius*1.35,-body.radius*1.35,body.radius*2.7,body.radius*2.7);}
    if (!atlasReady && body.kind === 'normal') { ctx.strokeStyle = '#b9aaff55'; ctx.lineWidth = 4; for (let y = -body.radius; y < body.radius; y += 9) { ctx.beginPath(); ctx.moveTo(-body.radius, y); ctx.quadraticCurveTo(0, y + 5, body.radius, y); ctx.stroke(); } }
    if (!atlasReady && body.kind === 'small') { ctx.fillStyle = '#24172d88'; for (let i = 0; i < 5; i++) { ctx.beginPath(); ctx.arc(Math.sin(i * 2.2) * body.radius * .55, Math.cos(i * 1.7) * body.radius * .5, body.radius * (.1 + i % 2 * .08), 0, Math.PI * 2); ctx.fill(); } }
    if (!atlasReady && body.kind === 'large') { ctx.strokeStyle = '#8affdb55'; ctx.lineWidth = 5; for (let y = -body.radius; y < body.radius; y += 12) { ctx.beginPath(); ctx.moveTo(-body.radius, y); ctx.lineTo(body.radius, y + 4); ctx.stroke(); } }
    ctx.restore(); if (atlasReady && atlasIndex === 5) ctx.drawImage(this.celestialAtlas, 1024, 512, 512, 512, -body.radius * 1.65, -body.radius * 1.65, body.radius * 3.3, body.radius * 3.3); if (['station','satellite','defenseNode'].includes(body.kind)) this.artificialBody(ctx, body); ctx.strokeStyle = '#ffffff22'; ctx.beginPath(); ctx.arc(0, 0, body.radius, 0, Math.PI * 2); ctx.stroke();
    if (body.route !== 'start') { ctx.rotate(Math.PI / 2); ctx.fillStyle = body.glow; ctx.font = '800 9px ui-monospace,monospace'; ctx.textAlign = 'center'; ctx.fillText(body.label, 0, body.captureRadius + 17); } ctx.restore();
  }
  artificialBody(ctx, body) { ctx.save(); ctx.rotate(performance.now() * .00035 * body.orbitSpeed); ctx.shadowBlur = 13; ctx.shadowColor = body.glow; ctx.strokeStyle = body.glow; ctx.fillStyle = '#b9c9dc'; ctx.lineWidth = 2; if (body.kind === 'satellite') { ctx.fillRect(-body.radius * .25,-body.radius * .38,body.radius * .5,body.radius * .76); ctx.fillStyle='#245c9b'; ctx.fillRect(-body.radius*1.25,-body.radius*.32,body.radius*.78,body.radius*.64); ctx.fillRect(body.radius*.47,-body.radius*.32,body.radius*.78,body.radius*.64); } else { ctx.beginPath(); ctx.arc(0,0,body.radius*.52,0,Math.PI*2); ctx.fill(); ctx.stroke(); ctx.beginPath(); ctx.ellipse(0,0,body.radius*1.28,body.radius*.42,0,0,Math.PI*2); ctx.stroke(); if(body.kind==='defenseNode'){ctx.fillStyle='#ff516d';ctx.beginPath();ctx.arc(body.radius*.65,0,body.radius*.16,0,Math.PI*2);ctx.fill();} } ctx.restore(); }
  atlasIndex(body) { const map = { normal: 1, large: 1, storm: 1, aurora: 1, volcanic: 2, small: 2, dwarf: 2, ember: 2, ice: 3, crystal: 3, pulsar: 3, desert: 4, toxic: 4, ringMoon: 4, hub: 5, station: 5, satellite: 5, defenseNode: 5 }; return map[body.kind] ?? 1 + body.id % 5; }
  modernAtlasIndex(body){const map={aurora:0,roseGiant:1,abyss:2,goldRing:3,crystal:4,pulsar:5,canyon:6,whiteStorm:7};return map[body.kind]??-1;}
  debris(ctx, item) { ctx.save();ctx.translate(item.x,item.y);ctx.rotate(item.rotation);if(item.kind==='energy'){ctx.globalCompositeOperation='screen';ctx.shadowBlur=24;ctx.shadowColor='#62eaff';const g=ctx.createRadialGradient(0,0,0,0,0,item.size*2.3);g.addColorStop(0,'#fff');g.addColorStop(.18,'#88ffff');g.addColorStop(.55,'#348cffcc');g.addColorStop(1,'#562cff00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,item.size*2.3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b9ffff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,item.size*1.1,0,Math.PI*2);ctx.stroke();}else if(item.kind==='laser'){ctx.globalCompositeOperation='screen';ctx.shadowBlur=18;ctx.shadowColor='#ff3d7f';const g=ctx.createLinearGradient(-item.size*7,0,item.size*2,0);g.addColorStop(0,'#ff2e7400');g.addColorStop(.55,'#ff3b8c');g.addColorStop(1,'#fff');ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(-item.size*7,-item.size*.38,item.size*9,item.size*.76,item.size*.38);ctx.fill();}else{const ready=this.hazardAtlas.complete&&this.hazardAtlas.naturalWidth;if(ready){const kindIndex={mine:0,debris:4,human:2}[item.kind]??4,index=item.variant??kindIndex,sw=this.hazardAtlas.naturalWidth/4,sh=this.hazardAtlas.naturalHeight/2,sx=index%4*sw,sy=Math.floor(index/4)*sh,size=item.kind==='human'?item.size*4.6:item.size*3.7;ctx.shadowBlur=18;ctx.shadowColor=item.kind==='debris'?'#ff8a3d':'#ff334f';ctx.drawImage(this.hazardAtlas,sx,sy,sw,sh,-size/2,-size/2,size,size);ctx.shadowBlur=0;}else{ctx.fillStyle='#ff425f';ctx.shadowBlur=15;ctx.shadowColor='#ff425f';ctx.beginPath();ctx.arc(0,0,item.size,0,Math.PI*2);ctx.fill();}}ctx.restore(); }
  trails(ctx) { const trail = this.engine.ufo.trail; if (trail.length < 2) return; const g = ctx.createLinearGradient(trail[0].x, trail[0].y, trail.at(-1).x, trail.at(-1).y); g.addColorStop(0, '#55e9ff00'); g.addColorStop(1, '#73ffd7dd'); ctx.strokeStyle = g; ctx.lineWidth = 3; ctx.beginPath(); trail.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); ctx.stroke(); }
  ufo(ctx, ufo) { ctx.save(); ctx.translate(ufo.x, ufo.y); ctx.rotate(ufo.angle); if(ufo.mode==='orbit'&&ufo.orbitDirection<0)ctx.scale(1,-1); if (ufo.boostTime > 0) this.booster(ctx, ufo.boostTime / .48); this.drawUfoShape(ctx, 1); ctx.restore(); }
  booster(ctx, strength) { const flicker = .76 + Math.random() * .24; ctx.save(); ctx.globalCompositeOperation = 'screen'; const length = (48 + 48 * strength) * flicker, plume = ctx.createLinearGradient(-28, 0, -28 - length, 0); plume.addColorStop(0, '#ffffff'); plume.addColorStop(.18, '#63f5ff'); plume.addColorStop(.62, '#346dffbb'); plume.addColorStop(1, '#7c36ff00'); ctx.fillStyle = plume; ctx.shadowBlur = 20; ctx.shadowColor = '#48dfff'; ctx.beginPath(); ctx.moveTo(-28, -11); ctx.quadraticCurveTo(-50 - length * .4, 0, -28 - length, 0); ctx.quadraticCurveTo(-50 - length * .4, 0, -28, 11); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#ffcf67'; for (let i = 0; i < 7; i++) { const x = -44 - Math.random() * length, y = (Math.random() - .5) * 20; ctx.globalAlpha = 1 - Math.abs(x + 44) / length; ctx.fillRect(x, y, 2 + Math.random() * 3, 2); } ctx.restore(); }
  drawUfoShape(ctx, scale) { ctx.scale(scale, scale); if (this.ufoImage.complete && this.ufoImage.naturalWidth) { ctx.shadowBlur = 15; ctx.shadowColor = '#54eaff'; ctx.drawImage(this.ufoImage, -52, -35, 104, 69); ctx.shadowBlur = 0; return; } ctx.shadowBlur = 18; ctx.shadowColor = '#61efff'; ctx.fillStyle = '#75efff'; ctx.beginPath(); ctx.ellipse(0, 2, 18, 7, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#afa0ff'; ctx.beginPath(); ctx.arc(2, -4, 8, Math.PI, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; }
  introUfo(ctx, progress, side) { const failure = Math.max(0, (progress - .48) / .52), x = side + 270 + Math.sin(progress * 31) * failure * 18, y = 920 - Math.min(progress / .64, 1) * 210; ctx.save(); ctx.translate(x, y); ctx.rotate(Math.sin(progress * 27) * failure * .09); this.drawUfoShape(ctx, 1.55); if (failure > 0) { const pulse = .55 + Math.sin(progress * 70) * .45; ctx.globalAlpha = failure; for (let i = 0; i < 14; i++) { const a = i * 2.39 + progress * 13, d = 35 + ((progress * 190 + i * 17) % 58); ctx.fillStyle = i % 3 ? '#ffb34d' : '#64eaff'; ctx.shadowBlur = 8; ctx.shadowColor = ctx.fillStyle; ctx.fillRect(Math.cos(a) * d - 1, Math.sin(a) * d - 1, 2 + i % 2, 2 + i % 3); } ctx.shadowBlur = 0; ctx.strokeStyle = `rgba(255,92,95,${pulse})`; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(0, 0, 58 + pulse * 6, -.35, .35); ctx.stroke(); ctx.fillStyle = '#ff7184'; ctx.font = '900 10px ui-monospace,monospace'; ctx.textAlign = 'center'; ctx.fillText(failure < .55 ? 'ENGINE INSTABILITY' : 'NAVIGATION FAILURE', 0, 72); ctx.fillStyle = '#95a9c8'; ctx.font = '700 7px ui-monospace,monospace'; ctx.fillText(failure < .55 ? 'THRUSTER 03: OFFLINE' : 'GRAVITY LOCK DETECTED', 0, 85); } ctx.restore(); }
  showReaction(index,duration=1.2){this.reactionIndex=index;this.reactionUntil=performance.now()+duration*1000;}
  drawReaction(ctx,index,x,y,size=72){if(!this.reactionAtlas.complete||!this.reactionAtlas.naturalWidth)return;const sw=this.reactionAtlas.naturalWidth/3,sh=this.reactionAtlas.naturalHeight/2,sx=index%3*sw,sy=Math.floor(index/3)*sh;const pop=.92+Math.sin(performance.now()*.012)*.05;ctx.save();ctx.translate(x,y);ctx.rotate(Math.sin(performance.now()*.007)*.04);ctx.scale(pop,pop);ctx.shadowBlur=18;ctx.shadowColor='#62eaff';ctx.drawImage(this.reactionAtlas,sx,sy,sw,sh,-size/2,-size/2,size,size);ctx.restore();}
  activeReaction(ctx,side,e){if(performance.now()>this.reactionUntil)return;const x=side+e.ufo.y+66,y=VIEW_HEIGHT+e.cameraX-e.ufo.x-54;this.drawReaction(ctx,this.reactionIndex,x,y,74);}
  failureAlert(ctx,progress,side){const failure=Math.max(0,(progress-.48)/.52);if(failure<=0)return;const x=side+270,y=610;ctx.save();ctx.globalAlpha=Math.min(1,failure*1.8);const width=286;ctx.fillStyle='#160b20dd';ctx.strokeStyle='#ff536d';ctx.lineWidth=1;ctx.fillRect(x-width/2,y,width,74);ctx.strokeRect(x-width/2,y,width,74);ctx.fillStyle='#ff657a';ctx.textAlign='center';ctx.font='900 12px ui-monospace,monospace';ctx.fillText('FLIGHT CONTROL BURNOUT',x,y+22);ctx.fillStyle='#f4f7ff';ctx.font='800 8px ui-monospace,monospace';ctx.fillText('MANUAL STEERING LOST',x,y+41);ctx.fillStyle='#65f4d0';ctx.fillText('GRAVITY ASSIST ONLY',x,y+57);for(let i=0;i<5;i++){const smokeY=720-((progress*130+i*21)%95),smokeX=x-18+Math.sin(progress*12+i)*22;ctx.globalAlpha=failure*(.2+i*.05);ctx.fillStyle='#64728d';ctx.beginPath();ctx.arc(smokeX,smokeY,8+i*2,0,Math.PI*2);ctx.fill()}ctx.restore();this.drawReaction(ctx,2,x+105,715,78);}
  vignette(ctx) { const g = ctx.createRadialGradient(this.viewWidth / 2, VIEW_HEIGHT / 2, VIEW_HEIGHT * .28, this.viewWidth / 2, VIEW_HEIGHT / 2, Math.max(this.viewWidth, VIEW_HEIGHT) * .72); g.addColorStop(0, '#0000'); g.addColorStop(1, '#01030aaa'); ctx.fillStyle = g; ctx.fillRect(0, 0, this.viewWidth, VIEW_HEIGHT); }
}
